### ISSUE TITLE
NEXTOR 2.1 Alpha-2 bug BASIC MAPDRV

### ISSUE THREAD

**Issue by alessandroscaccia** [Konamiman/Nextor#31]
Hi,

I have a megaflashrom + sd and 2 partition of 16M each, created with call fdisk command. In both partitions there are nextor file and msx-dos files.
I’m using nextor 2.1 with msx1 mode and i have a strange issue:

if use in msx-dos2 mode and type:
mapdrv d: 2 1 0

work fine

if use in basic mode (type 1 at boot, so going in msx1 mode) the command:
call mapdrv (“D:”,2,1)

return “Bad drive name” or “Invalid device driver” if used call mapdrv (“D:”,2,1,0)

is a bug?
>
>
>
Best Regards

**Comment by Konamiman** [comment]
Hi! In my tests I have found that `call mapdrv (“D:”,2,1)` gives "Invalid device driver" which is expected because D: is not assigned to anything by default; and `call mapdrv (“D:”,2,1,0)` works as expected.

Can you please give me more details about your setup? What version of Nextor are you using? Do you have any other storage device in use?

**Comment by Konamiman** [comment]
I'm closing this since it's over one year old, I can't reproduce it and nobody else reported it. I'll reopen if you can provide further information.
