### ISSUE TITLE
Nextor IDE driver/BIOS causes a weird effect when CF card not present in IDE device

### ISSUE THREAD

**Issue by Wierzbowsky** [Konamiman/Nextor#64]
On a computer with 2 floppy disk drives (or Gotek + FDD drives: Yamaha YIS805/256 for example) and an IDE-capable device like Carnivore2 or FDD/IDE controller with IDE driver 0.1.5 or 0.1.7 there appears a strange effect when there's no card in the IDE device. After a failure to detect the card by the IDE driver, booting continues from drive A: and MSX-DOS gets successfully loaded from a diskette/emulator. However, the drive's A: LED stays always on and the second floppy drive B: becomes inaccessible. When there's a card in the IDE device, this doesn't happen. Also if the original Sunrise BIOS is used in the FDD/IDE controller, everything works fine.

So there's some sort of anomaly when the Nextor's IDE driver/BIOS can't find the card in the device - it not only disables the second floppy drive, but keeps the first drive always active.

**Comment by Konamiman** [comment]
About drive B: becoming inaccessible: remember that the "standard" (built without customizations) Nextor ROMs invert the behavior of the CTRL key by default, so you won't see the second FDD unless you press CTRL while botting.

About the drive LED being always on: I've been able to reproduce in blueMSX emulating the Philips NMS 8280. If I boot pressing CTRL so that drive B: becomes accessible, and I access drive B:, then the led for drive A: goes off and the led for drive B: stays on. Interestingly, this happens only when there is a disk inserted in drive A: at the time of booting.

It would be interesting to know if that happens with other (non-IDE) Nextor drivers as well.

**Comment by Konamiman** [comment]
Mystery solved and issue (will be) fixed: https://github.com/Konamiman/Nextor/pull/107
