### ISSUE TITLE
EP.COM not working

### ISSUE THREAD

**Issue by AxelStone** [Konamiman/Nextor#83]
Hello Konamiman, EP.COM is not working on Nextor, this is the failure:

Not a DOS disk reading drive A:   

Of course A: changes depending on where the .DSK is located.

The Nextor version I'm using:

Nextor Kernel version 2.1.0
NEXTOR.SYS version 2.10
COMMAND2.COM version 2.44

Thanks.

**Comment by Konamiman** [comment]
Hi, it's better to write in English so that everybody can follow up on the issues. Anyway I've translated your text.

As far as I know EP.COM is MegaSCSI only and relies on internal/undocumented code and variables of MSX-DOS 2 that might not be the same in Nextor, thus it's entirely normal that it doesn't work. Anyway, may I ask why do you want to use that tool if Nextor has already a built-in mechanism to use disk images?

**Comment by AxelStone** [comment]
Buen apunte, gracias por el cambio 🙂. Oye por cierto te veo muy activo en el hilo del nuevo MSX, ¿Hay ganas de cosas frescas? 🙂

Es que hablando de MSX nuevos hace poco tenemos el VR entre nosotros, pero veo muchas sensaciones encontradas, la mayoría son críticas negativas. ¿Has llegado a probarlo? ¿Es tan chungo como dicen?

Un saludo 🙂

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by AxelStone** [comment]
Por cierto perdona no te respondí, lo hago en el GitHub original esta tarde que ahora estoy en el trabajo. Es cierto tenemos el emufile así que en principio lo lógico es usarlo.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by grauw** [comment]
Hey AxelStone,

Note that you’re replying publicly to GitHub and not privately to Konamiman ;).

**Comment by AxelStone** [comment]
Thanks for your advice @grauw ^_^! Ok comments removed, not related at all with the content of the issue. About the issue just to comment that you are right @Konamiman , we already have emufile in Nextor so it makes sense to use it instead of EP.

Best regards.

**Comment by Konamiman** [comment]
Great. Closing this then.
